### ISSUE TITLE
Missing install script / hosting?

### ISSUE THREAD

**Issue by machinaut** [fetchrobotics/fetch_robots#17]
The on-robot installation script is pointed at `http://install.fetchrobotics.com/install-scripts/install-fetch.bash` but that domain appears to be down/gone.

Is the `/bin/Fetch-full-install.bash` script up-to-date?

**Comment by moriarty** [comment]
First, sorry for the long delay. As this repository doesn't actually contain code, and is very stable, it can get forgotten.

That domain might have changed, but I don't know when and where. @erelson will be able to answer your question.

I took a look and couldn't find that script, and if it is up-to-date, it won't be for long as we're preparing a melodic release.

Our documentation is now hosted at: http://docs.fetchrobotics.com/index.html

**Comment by erelson** [comment]
To follow-up, install.fetchrobotics.com isn't something we use (we envisioned possibly using it years ago, but that never materialized).

We do make the installer available if you reach out to us at support.fetchrobotics.com.
