### ISSUE TITLE
No diagnotics aggregator running

### ISSUE THREAD

**Issue by ensonic** [fetchrobotics/fetch_robots#18]
It would be awesome to have a diagnostics aggregator configured and running
http://wiki.ros.org/diagnostic_aggregator
Running the node is easy, what is missing is a configuration for the analyzers.

**Comment by erelson** [comment]
There's a configuration available in a pull req, which should hopefully still work: https://github.com/fetchrobotics/fetch_robots/pull/6

**Comment by ensonic** [comment]
Thanks, it would be great to have this merged as a starting point. I've placed some comments on the PR for some details.

**Comment by mikeferguson** [comment]
#6 is merged and released -- will probably make it into debians in the next several days -- watch the mailing list for an announce
