### ISSUE TITLE
TODO: switch to official SICK drivers

### ISSUE THREAD

**Issue by moriarty** [fetchrobotics/fetch_robots#35]
We depend on `ros-melodic-sick-tim` package from https://github.com/uos/sick_tim/ which for the purpose of the upcoming release to melodic fetchrobotics/fetch_ros#63 is fine.

But we should switch over to the official drivers: https://github.com/SICKAG/sick_scan which is `ros-melodic-sick-scan` at some point in the future.

This won't be for the initial ros-melodic release, because we want that to get out with the next melodic sync and won't have time for the additional tests.

@chadrockey are you aware of any major differences?

**Comment by chadrockey** [comment]
No, but I haven't looked into the TIM stuff in forever.

I'll look into this in the coming weeks.

**Comment by moriarty** [comment]
I'm going to close this now and open a ticket internally as it's not an issue, the `ros-melodic-sick-tim` package is working now.

@rctoris the original request came via an email.
