### ISSUE TITLE
[Fetch] Have to disable `eth1` interface to access internet

### ISSUE THREAD

**Issue by umhan35** [fetchrobotics/fetch_robots#62]
After updating the system at one point, I found Fetch (ssh'ed into) cannot access internet (ping 1.1.1.1 or ping  github.com).

What I have to do is disable `eth1` network interface. But this disable Fetch's arm as well.

I also tried "Use this connection only for resources on its network" for eth1, but the apply button becomes gray so I cannot click on it.

How to fix it?

I am using Ubuntu 18.04.

Thanks!

**Comment by umhan35** [comment]
Fixed by removing the `gateway4` line from `/etc/netplan/99-fetch-ethernet.yaml`

http://docs.fetchrobotics.com/indigo_to_melodic.html#ensuring-robot-s-ethernet-ports-are-configured-correctly

**Comment by erelson** [comment]
Glad to hear past me already solved that issue! I had forgotten about that fix. Cheers!
